### ISSUE TITLE
Passing internal properties to cloned children

### ISSUE THREAD

**Issue by jourdain** [plotly/dash-vtk#3]
I would like to do the following which works with react but not when used inside dash.

The idea is that parent react element would pass addOn properties to their children. The code below highlight the problem.

```
import React from 'react';

// ------------------------------------------------------------------
// Component A
// ------------------------------------------------------------------

function ComponentA(props) {
  const addOnProps = {
    a: props.name,
  };
  const childrenWithAddOnProp = React.Children.map(props.children, child => React.cloneElement(child, addOnProps));
  return (
    <li>
      Inside Component A with name: {props.name}
      <ul>
        {childrenWithAddOnProp}
      <ul>
    </li>
  );
}

ComponentA.defaultProps = {
  name: 'a'
};

ComponentA.propTypes = {
  name: PropTypes.string,
};

// ------------------------------------------------------------------
// Component B
// ------------------------------------------------------------------

function ComponentB(props) {
  const addOnProps = {
    a: props.a,
    b: props.name,
  };
  const childrenWithAddOnProp = React.Children.map(props.children, child => React.cloneElement(child, addOnProps));
  return (
    <li>
      Inside Component B with name: {props.name} and A is {props.a}
      <ul>
        {childrenWithAddOnProp}
      <ul>
    </li>
  );
}

ComponentB.defaultProps = {
  name: 'b'
};

ComponentB.propTypes = {
  name: PropTypes.string,
};

// ------------------------------------------------------------------
// Component C
// ------------------------------------------------------------------

function ComponentC(props) {
  return (
    <li>
      My name is {props.name}, A is {props.a} and B is {props.b}
    </li>
  );
}

ComponentC.defaultProps = {
  name: 'c'
};

ComponentC.propTypes = {
  name: PropTypes.string,
};


// ------------------------------------------------------------------
// JSX
// ------------------------------------------------------------------

<ComponentA>
  <ComponentB>
    <ComponentC name="c1" />
    <ComponentC name="c2" />
    <ComponentC name="c3" />
  </ComponentB>
  <ComponentB name="NewB">
    <ComponentC name="OtherC"/>
  </ComponentB>
</ComponentA>

```

**Comment by alexcjohnson** [comment]
I think this happens because Dash components are actually wrapped in a couple of extra layers - a context consumer and a thing we call a "TreeContainer" - so when you ask for a certain dash component in Python, the React component you asked for is a couple of layers beneath that. It's a bit tricky to read, but the wrapping I'm talking about takes place [here](https://github.com/plotly/dash/blob/3402cb8f67466bcee8776b1d07dd3134d08bda76/dash-renderer/src/TreeContainer.js#L71-L79).

Two alternative approaches I can recommend:
1. Is there really a good reason to be creating nested Dash components? Or could you instead create a single `VtkView` component that has a nested data structure fed into it? That would be more like what we do with most of our other complex components (plotly.js graphs, dash_table, various dash_bio components...) and likely has lower overhead for a single render. The downside is if just a small part changes you may need to shuffle more data around than you would just updating that part, although if and when we finish up the partial prop updates project we have simmering, this penalty will go away.
2. If you want to keep the current component structure, can you instead use a context provider/consumer pair? ie the `VtkView` component provides the context, and inner components consume that as desired. Looks like other intermediate-level components would do the same, and you'd be able to get away from the various `// pass by parent` props that you don't want to expose to users anyway.

**Comment by xhlulu** [comment]
> Is there really a good reason to be creating nested Dash components? Or could you instead create a single VtkView component that has a nested data structure fed into it? That would be more like what we do with most of our other complex components (plotly.js graphs, dash_table, various dash_bio components...) and likely has lower overhead for a single render.

I initially suggested a multi-components library since it would feel more similar to `dash-bootstrap-components`, but since this might too difficult to achieve I think a single-component library (which @jourdain initially suggested) with well documented behavior is a good idea.

**Comment by xhlulu** [comment]
For future references I made [this repository](https://github.com/xhlulu/nested_children) that reproduces the error.

**Comment by jourdain** [comment]
Thanks @alexcjohnson and @xhlulu. I guess II'll go with (1) as a first step. The option (2) that I was trying to implement was to provide more flexibility and allow to only update subset of the data of the scene that actually change and reduce the network communication with the following example in mind:

> if you have a mesh that has time dependent data, then you can simply update the field without touching any of the scene definition or mesh coordinate and topology.

I was also thinking about using the multi-context approach for handling the component wrapping that happen with dash. But I will need more time to iron out such logic as I don't run my update phase in `render()` call to allow prop ref comparison and prevent extra processing when things don't change. Anyhow, it should be doable, but much more involving than what I was hoping for.

If I go with (1) to start simple. Does it mean that I should capture the scene definition inside a single property as a JSON structure. In which case each time you want to change the color of an element or update a field (i.e. Temperature, Pressure) of a mesh, you will have to send all the meshes and fields again? Do you have good pattern or convention to follow for that?

Just to give you an idea of what a scene could look like here is an example of what I'm thinking for an implementation of (1).

```
...
```

**Comment by jourdain** [comment]
I did it via Context and it is working great... 

I guess I will pursue that path as it will allow way more capabilities than having a mono-components...

We can always provide helpers for the most common patterns to only have a 1 level deep (<view><obj1/><obj2/></view>) at the dash level.
