### ISSUE TITLE
Is it possible to add a colorbar?

### ISSUE THREAD

**Issue by solarjoe** [plotly/dash-vtk#65]
Is there a build-in way in dash-vtk to add a colorbar, e.g. to a PointCloudRepresentation?

I could not find anything anything about this, except [this workaround](https://github.com/shkiefer/pyAnsys_DPF_dash/blob/main/pyAnsys_DPF_dash.py) where a colorbar is added using an empty `plotly go.Figure()' and someone [asking](https://community.plotly.com/t/colorbar-colormap-for-scalar-in-dash-vtk-view/58708) for it in the Plotly forum.

**Comment by jourdain** [comment]
Ideally PointCloudRepresentation should expose the same properties as the default [GeometryRepresentation](https://github.com/Kitware/react-vtk-js/blob/master/src/core/GeometryRepresentation.js#L315-L329). 

That seems to be the case in [react-vtk-js](https://github.com/Kitware/react-vtk-js/blob/master/src/representations/PointCloudRepresentation.js) but dash-vtk was not updated to reflect it.

Otherwise someone with the current version could do what we do [inside PointCloudRepresentation](https://github.com/Kitware/react-vtk-js/blob/master/src/representations/PointCloudRepresentation.js#L37-L60) but using dash-vtk directly.

**Comment by solarjoe** [comment]
I just saw that someone already opened a PR for this feature. 
https://github.com/plotly/dash-vtk/pull/61

**Comment by solarjoe** [comment]
But the PR does that, right?

**Comment by jourdain** [comment]
No, the PR, just expose those props in GeometryRepresentation not in PointCloudRepresentation
